use_frameworks!

platform :ios, '13.0'

target 'GGPermission_Example' do
  # Core 会被 Photo / Camera 自动带进来，不用显式写
  pod 'GGPermission', :path => '../'
  pod 'GGPermission/Location', :path => '../'

  target 'GGPermission_Tests' do
    inherit! :search_paths
  end
end